language: generic 
sudo : required
services:
  - docker

before_install:
  - docker build -t eddierock55/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eddierock55/docker-react npm run test -- --coverage